#!/bin/sh

# CIDRnt-locales-map-gen.sh - Generate CIDRnt locales map from RIR statistics.

set -eu

OUT="${1:-./resources/locales_map/locales.map}"
TMP=$(mktemp -d)

trap 'rm -rf "$TMP"' EXIT

fetch() {

    if command -v curl >/dev/null 2>&1; then

        curl -fsSL "$2" -o "$TMP/$1"

    else

        wget -q -O "$TMP/$1" "$2"

    fi

}

fetch afrinic https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest

fetch apnic https://ftp.apnic.net/stats/apnic/delegated-apnic-extended-latest

fetch arin https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest

fetch lacnic https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest

fetch ripencc https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-extended-latest

awk -F'|' '
    ($3 == "ipv4" || $3 == "ipv6") && ($7 == "allocated" || $7 == "assigned") {
        cc = $2

        if (cc !~ /^[A-Z][A-Z]$/ || cc == "EU" || cc == "AP") next

        n[cc SUBSEP $1]++
        seen[cc] = 1
    }
    END {

        for (cc in seen) {
            best = ""; bestn = -1

            for (k in n) {
                split(k, a, SUBSEP)

                if (a[1] != cc) continue

                if (n[k] > bestn || (n[k] == bestn && a[2] < best)) {
                    best = a[2]; bestn = n[k]
                }

            }

            printf "%s|%s\n", cc, best
        }

    }
' "$TMP"/afrinic "$TMP"/apnic "$TMP"/arin "$TMP"/lacnic "$TMP"/ripencc | sort > "$TMP/map"

{
    printf '# Generated by %s for CIDRnt\n\n' "$(basename "$0")"
    printf '# This file maps ISO-3166 alpha-2 locales to their respective RIRs, it is not\n'
    printf '# strictly necessary and provided for convenience but only but may (will) be\n'
    printf '# be faster than the dynamic parsing fallback path if present.\n\n'
    printf '# Format: ISO-3166 alpha-2 locale|RIR\n\n'

    cat "$TMP/map"

} > "$OUT"
